# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LingoChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LingoChat
  pod 'Bond'
  pod 'Alamofire'
  pod 'JWTDecode', '~> 2.2'
end
